// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnC7_1Ot4mxPieD1AaeCWm-4K3X_GIx5s',
    appId: '1:1044608870893:android:90102b42e9de1178021fe4',
    messagingSenderId: '1044608870893',
    projectId: 'theguideliverpool-51e81',
    storageBucket: 'theguideliverpool-51e81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYzfDbY-WTHY4_0jRTZBXlDKqxrMdef64',
    appId: '1:1044608870893:ios:c472d230ab798a35021fe4',
    messagingSenderId: '1044608870893',
    projectId: 'theguideliverpool-51e81',
    storageBucket: 'theguideliverpool-51e81.appspot.com',
    androidClientId: '1044608870893-4lqmkl9u2vcrg36kra9stqna6sqva0sh.apps.googleusercontent.com',
    iosClientId: '1044608870893-qdujufpfbe9fe1lheg8oiec7grg2fvbu.apps.googleusercontent.com',
    iosBundleId: 'com.theguideliverpool.theguideapp',
  );
}
