/// Flutter icons PeeplIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PeeplIcons
///      fonts:
///       - asset: fonts/PeeplIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PeeplIcons {
  PeeplIcons._();

  static const _kFontFam = 'PeeplIcons';
  static const String? _kFontPkg = null;

  static const IconData ppl_circles_02 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
